name: hohoedu_attendance
description: "It is used to check the student's attendance in hoho academy"

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^1.2.1
  flutter_dotenv: ^5.0.2
  connectivity_plus: ^5.0.2
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: NotoSansKR-Regular
      fonts: 
        - asset: assets/fonts/NotoSansKR-Regular.ttf
    - family: BMJUA
      fonts: 
        - asset: assets/fonts/BMJUA.ttf